version: "3.8"
services:
  product-service:
    build: ./product_service/
    container_name: prodcut-service
    environment:
      API_PORT: ":3000"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "upera"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB_NAME: "product-service-db"
      KAFKA_URL: "kafka:9092"
      KAFKA_TOPIC: "upera"
      KAFKA_UPDATE_P: "1"
      KAFKA_CREATE_P: "0"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - kafka

  history-service:
    build: ./history_service/
    container_name: history-service
    environment:
      API_PORT: ":3000"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB_NAME: "history-data-DB"
      MONGO_COLLECTION_NAME: "history-data"
      KAFKA_URL: "kafka:9092"
      KAFKA_TOPIC: "upera"
      KAFKA_UPDATE_P: "1"
      KAFKA_CREATE_P: "0"
    ports:
      - "3001:3000"
    depends_on:
      - "mongo"
      - "product-service"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "product-service-db"
      POSTGRES_USER: "upera"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
