version: "3.8"
services:
  product-service:
    build: ./product_service/
    container_name: prodcut-service
    environment:
      API_PORT: ":3000"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "upera"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB_NAME: "product-service-db"
      KAFKA_URL: "0.0.0.0:29092,0.0.0.0:29093"
      KAFKA_TOPIC: "upera"
      KAFKA_UPDATE_P: "1"
      KAFKA_CREATE_P: "0"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      # - kafka1
      # - kafka2

  history-service:
    build: ./history_service/
    container_name: history-service
    environment:
      API_PORT: ":3000"
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_DB_NAME: "history-data-DB"
      MONGO_COLLECTION_NAME: "history-data"
    ports:
      - "3001:3000"
    depends_on:
      - "mongo"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "product-service-db"
      POSTGRES_USER: "upera"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"

  # kafka1:
  #   extends:
  #     file: kafka-compose.yml
  #     service: kafka1

  # kafka2:
  #   extends:
  #     file: kafka-compose.yml
  #     service: kafka2

  # kafka-ui:
  #   extends:
  #     file: kafka-compose.yml
  #     service: kafka-ui

  # zookeeper:
  #   extends:
  #     file: kafka-compose.yml
  #     service: zookeeper
