version: "3.8"
services:
  product-service:
    build: ./product_service/
    container_name: prodcut-service
    environment:
      API_PORT: ":3000"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "upera"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB_NAME: "product-service-db"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - kafka-ui

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "product-service-db"
      POSTGRES_USER: "upera"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"

  kafka1:
    extends:
      file: kafka-compose.yml
      service: kafka1

  kafka2:
    extends:
      file: kafka-compose.yml
      service: kafka2

  kafka-ui:
    extends:
      file: kafka-compose.yml
      service: kafka-ui

  zookeeper:
    extends:
      file: kafka-compose.yml
      service: zookeeper
